image: node:16.13

stages:
    - install-dependencies
    - test
    - build

Install Dependencies:
    stage: install-dependencies
    script:
        - yarn install
    cache:
        key: ${CI_COMMIT_BRANCH}
        paths:
            - node_modules

ESLinter:
    stage: test
    script:
        - node ./node_modules/eslint/bin/eslint.js src/
    cache:
        key: ${CI_COMMIT_BRANCH}
        paths:
            - node_modules

Build Nitro:
    stage: build
    script:
        - cp .env.example .env
        - cp src/renderer-config.json.example src/renderer-config.json
        - cp src/ui-config.json.example src/ui-config.json
        - yarn build-prod
    cache:
        key: ${CI_COMMIT_BRANCH}
        paths:
            - node_modules
    artifacts:
        expire_in: 2 weeks
        paths:
            - dist/*
